apiVersion: v1
kind: Service
metadata:
  name: alamesafrontendservice
spec:
  selector:
    app: alamesafrontendlabel
  type: LoadBalancer
  ports:
    - name: alamesafrontendport
      port: 3000
      targetPort: 3000
  externalIPs:
    - 192.168.49.2
