apiVersion: apps/v1
kind: Deployment
metadata:
  name: alamesafrontenddeployment
spec:
  selector:
    matchLabels:
      app: alamesafrontendlabel
  replicas: 1
  template:
    metadata:
      labels:
        app: alamesafrontendlabel
    spec:
      containers:
        - name: alamesafrontend
          imagePullPolicy: Never
          image: alamesa-frontend 
          ports:
            - containerPort: 3000
